### ISSUE TITLE
Question about a related problem

### ISSUE THREAD

**Issue by matthiasfeist** [rowanwins/smallest-enclosing-circle#7]
Hi.

I know this is not an issue but your solves a similar problem I believe. I am looking for a library which implements the "minimum bounding box by width" algorithm.
Example here: http://resources.arcgis.com/en/help/main/10.1/0017/GUID-EFBA5DB8-A161-4FE1-B2CB-792B65DC1469-web.png

Do you know any?
Thanks a lot!

**Comment by matthiasfeist** [comment]
Sorry for the spam here. I found that it was actually rather simple to implement and did it: https://www.npmjs.com/package/geojson-minimum-bounding-rectangle

Again sorry for the spam, please feel free to delete this issue completely.

**Comment by rowanwins** [comment]
Sorry for the slow reply, glad you got it sorted @matthiasfeist.
I had a quick look at your implementation, certainly the output looks really neat! 
It would be interesting to add some benchmark stats to see how it performs, and perhaps some notes about what you've implemented (eg whether it's a rotating calipers approach or something else), but those are really minor nitpicks on what looks to be an otherwise excellent library!

**Comment by matthiasfeist** [comment]
Good idea. I'll think about it. :) 👍
